### ISSUE TITLE
Update pubspec.yaml to include Dart 2.0

### ISSUE THREAD

**Issue by ShadowStrikerJ** [ZaraclaJ/audio_recorder#12]
As far as I can tell, a few of the past commits have brought this plugin up to date with the current Dart version, and should therefore be updated to reflect that so it can be safely used in up to date Flutter apps.
If I am wrong in this, let me know if there is any way I can help the process along and I would love to contribute.

**Comment by ZaraclaJ** [comment]
Done ! thanks for your feed back
