### ISSUE TITLE
Widget tests are failing

### ISSUE THREAD

**Issue by mmcc007** [ZaraclaJ/audio_recorder#18]
Because `testWidgets()` is not run in real time, it appears to be not possible to make dart async calls to file system when testing widgets. Since this plugin accesses the file system in dart code, my tests for widgets that use this plugin are failing, for example, when calling `AudioRecorder.start()`. 

Google provides a [file system abstraction package](https://pub.dartlang.org/packages/file) that addresses this problem. I was able to use this package to get widget tests to work (using mocking). Required making a minor change to the plugin's dart code (1 new line, 1 modified line, no change to API). 

I can do a PR for this if interested (or add to existing PR #17). Let me know 👍

**Comment by mmcc007** [comment]
I needed to check-in the plugin fix to my github repo for my local CI build to work. So it is now part of PR #17. Hope that's ok.

**Comment by ZaraclaJ** [comment]
Plugin updated ! Thanks for your work :)
