### ISSUE TITLE
Reverse audio?

### ISSUE THREAD

**Issue by hosembafer** [ZaraclaJ/audio_recorder#19]
Is there a way to reverse audio after recording?

**Comment by ZaraclaJ** [comment]
What do you mean by reverse audio ?

**Comment by hosembafer** [comment]
I mean playing backward

**Comment by ZaraclaJ** [comment]
I think this is not the purpose of this plugin.
Once the audio is recorded, you can use it as you want. 
Maybe it exist a plugin to play audio backward ...
