### ISSUE TITLE
path_provider incompatible with contacts_service 0.2.2

### ISSUE THREAD

**Issue by TheHemantKaushik** [ZaraclaJ/audio_recorder#34]
Hi,

I am getting issue in adding `audio_recorder` package to project. This is because of `path_provider` package is incompatible with other packages. Error details:

> Because audio_recorder >=0.0.5 depends on path_provider ^0.4.1 and contacts_service 0.2.2 depends on path_provider ^0.5.0+1, audio_recorder >=0.0.5 is incompatible with contacts_service 0.2.2.
> So, because securityguard depends on both contacts_service 0.2.2 and audio_recorder ^0.0.6, version solving failed.

**Comment by therichiekumar** [comment]
I have same issue. @TheHemantKaushik can you resolve it?

**Comment by ZaraclaJ** [comment]
Fixed in the 1.0.0 version
