### ISSUE TITLE
erro，help me

### ISSUE THREAD

**Issue by lanjiachuan** [ZaraclaJ/audio_recorder#35]
audio_recorder-0.0.6/lib/audio_recorder.dart:49:13: Error: A constructor invocation can't have type arguments on the constructor name.
Try to place the type arguments on the class name.
        Map.from<String, Object>(await _channel.invokeMethod('stop'));

**Comment by yyang150** [comment]
ORZ.. same...

**Comment by yyang150** [comment]
> audio_recorder-0.0.6/lib/audio_recorder.dart:49:13: Error: A constructor invocation can't have type arguments on the constructor name.
> Try to place the type arguments on the class name.
> Map.from<String, Object>(await _channel.invokeMethod('stop'));

One solution might be using this [pkg](https://github.com/Apurv2017/audioRecorder2) instead

**Comment by sgon00** [comment]
hi, you can simply modify the source code from `Map.from<String, Object>(await _channel.invokeMethod('stop'));` to `Map.from(await _channel.invokeMethod('stop'));`. That's it. 

The only thing I don't understand is why all the recorder plugins record sound with VERY low volume. I tried many plugins. None of them give me high volume result. This is just very weird.

**Comment by ZaraclaJ** [comment]
Fixed in the 1.0.0 version
