### ISSUE TITLE
need to be updated for dart 2 preview.

### ISSUE THREAD

**Issue by jeanpaulcozzatti** [ZaraclaJ/audio_recorder#4]
libraries will need to be updated for dart 2 preview eventuallly.
it currently breaks on the preview which is the default for flutter.
'_Future' is not a subtype of type 'Future<bool>

https://groups.google.com/forum/#!topic/flutter-dev/H8dDhWg_c8I

**Comment by ZaraclaJ** [comment]
The v 0.0.2 of the plugin support Dart 2.
Thank you for your comment
