### ISSUE TITLE
Excuse me, How can I fix this problem?

### ISSUE THREAD

**Issue by KossFun** [ZaraclaJ/audio_recorder#44]
![微信截图_20191108143714](https://user-images.githubusercontent.com/49841387/68455060-5cb35400-0235-11ea-96e8-c0f63bc23ac6.png)

**Comment by mobydick-io** [comment]
I am experiencing the exact same problem.  Could you please fix this?  Thanks.

**Comment by timfreiheit** [comment]
this pr https://github.com/ZaraclaJ/audio_recorder/pull/43 fixes the issue

**Comment by DyaryRaoof** [comment]
same issue not fixed but #43  I am using the latest plugin version 1.0.1

**Comment by Halim78** [comment]
Hello, 
can you solve this problem?
thanks

**Comment by ZaraclaJ** [comment]
fix in 1.0.2
