### ISSUE TITLE
Exception miss kotlin files

### ISSUE THREAD

**Issue by alevittoria** [ZaraclaJ/audio_recorder#46]
Hello, when i try to import the library audio_recorder I receive this error:

Couldn't read file LocalFile: 'C:\Devel\flutter\.pub-cache\hosted\pub.dartlang.org\audio_recorder-1.0.1\android\src\main\kotlin\com\jordanalcaraz\audiorecorder\audiorecorder\AudioRecorderPlugin.kt' even though it exists. Please verify that this file has read permission and try again.

I don't know why it is searching for kotlin files and not java but the result it's I'm not able to use it

**Comment by DyaryRaoof** [comment]
having the same issue

**Comment by hugocbpassos** [comment]
Seems like this is related to the latest updates of Flutter. Happened to me right after updating to **v1.12.13+hotfix.5 stable**, but has been reported in **v1.11.0**: https://stackoverflow.com/questions/59122719/flutter-issues-after-flutter-upgrade-to-flutter-1-11-0-mac-os

**Comment by DyaryRaoof** [comment]
I am on the master branch. This error appears in iOS.
To solve it you need to locate your audio_recorder plugin inside flutter. then change the name of it's last child folder on android. You have to change it from audio_recorder to audiorecorder(remove the underscore).

**Comment by hugocbpassos** [comment]
Very weird. Perhaps this commit is related: https://github.com/ZaraclaJ/audio_recorder/commit/1039568f4f3c9deb2901fb877afede5898ce78d3

**Comment by xizhouhezai** [comment]
I had the same problem after I upgraded flutter

**Comment by JCPradelPH** [comment]
I am having the same issue after upgrading flutter to 1.12.13. Is there already a fix?

**Comment by AliAnilKocak** [comment]
I have the same problem. Flutter works correctly in version 1.9

```
git checkout v1.9
flutter doctor
```

**Comment by fabianogadenz** [comment]
having the same issue

**Comment by fabianogadenz** [comment]
@DyaryRaoof solved my problem. thanks

**Comment by Junddao** [comment]
change the folder name from 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\audio_recorder-1.0.1\android\src\main\java\com\jordanalcaraz\audiorecorder\**audio_recorder**' to 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\audio_recorder-1.0.1\android\src\main\java\com\jordanalcaraz\audiorecorder\**audiorecorder**'

**Comment by cavanlee** [comment]
@Junddao solved this issue.

**Comment by lpreimesberger** [comment]
thanks @Junddao  - stable and dev flutter don't like the underscore name - seems to affect a bunch of components.  :-(
